#!/usr/bin/env python3
"""
Assemble an Overleaf-ready LaTeX section summarizing per-window evaluation.

Inputs: results generated by tools/evaluate_windows.py under
results/addons/period_slices/<window>/{tables,figures}/

Output: results/addons/period_slices/period_report_section.tex
"""

import argparse
import os
import glob
from typing import List


def find_windows(base_dir: str) -> List[str]:
    subdirs = []
    for path in glob.glob(os.path.join(base_dir, '*')):
        if os.path.isdir(path) and os.path.exists(os.path.join(path, 'tables', 'risk.tex')):
            subdirs.append(os.path.basename(path))
    return sorted(subdirs)


def make_section(base_dir: str, out_path: str) -> None:
    windows = find_windows(base_dir)
    lines: List[str] = []
    lines.append('% Auto-generated period report section')
    lines.append('% Include this file in your Overleaf project')
    lines.append('')
    lines.append('\\section{Period-sliced Evaluation}')
    for w in windows:
        lines.append(f'\\subsection{{{w}}}')
        # Tables
        lines.append(f'\\input{{{os.path.join(base_dir, w, "tables", "risk.tex")}}}')
        lines.append(f'\\input{{{os.path.join(base_dir, w, "tables", "dist.tex")}}}')
        lines.append(f'\\input{{{os.path.join(base_dir, w, "tables", "summary.tex")}}}')
        # Key figures if present (wildcards)
        fig_dir = os.path.join(base_dir, w, 'figures')
        for fig in sorted(glob.glob(os.path.join(fig_dir, '*_distribution_comparison.pdf'))):
            lines.append(f'\\begin{{figure}}[h]')
            lines.append('  \\centering')
            lines.append(f'  \\includegraphics[width=0.8\\textwidth]{{{fig}}}')
            lines.append('  \\caption{Distribution comparison}')
            lines.append('\\end{figure}')
        for fig in sorted(glob.glob(os.path.join(fig_dir, '*_sequence_var_overlays.pdf'))):
            lines.append(f'\\begin{{figure}}[h]')
            lines.append('  \\centering')
            lines.append(f'  \\includegraphics[width=0.8\\textwidth]{{{fig}}}')
            lines.append('  \\caption{Sequence with VaR overlays}')
            lines.append('\\end{figure}')
        # Optional conditional coverage
        for fig in sorted(glob.glob(os.path.join(fig_dir, '*_conditional_coverage_var95.pdf'))):
            lines.append(f'\\begin{{figure}}[h]')
            lines.append('  \\centering')
            lines.append(f'  \\includegraphics[width=0.8\\textwidth]{{{fig}}}')
            lines.append('  \\caption{Conditional coverage by regime (95\% VaR)}')
            lines.append('\\end{figure}')
    # Combined summary table if exists
    summary_tex = os.path.join(base_dir, 'summary.tex')
    if os.path.exists(summary_tex):
        lines.append('')
        lines.append('\\section{Cross-window Summary}')
        lines.append(f'\\input{{{summary_tex}}}')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description='Build Overleaf-ready LaTeX section for period slices.')
    parser.add_argument('--base', default='results/addons/period_slices', help='Base period slices directory')
    parser.add_argument('--out', default='results/addons/period_slices/period_report_section.tex', help='Output .tex path')
    args = parser.parse_args()
    make_section(args.base, args.out)


if __name__ == '__main__':
    main()


